name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace Firebase placeholders
        run: |
          sed -i "s|%VITE_FIREBASE_API_KEY%|${{ secrets.VITE_FIREBASE_API_KEY }}|g" js/firebase-template.js
          sed -i "s|%VITE_FIREBASE_AUTH_DOMAIN%|${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}|g" js/firebase-template.js
          sed -i "s|%VITE_FIREBASE_PROJECT_ID%|${{ secrets.VITE_FIREBASE_PROJECT_ID }}|g" js/firebase-template.js
          sed -i "s|%VITE_FIREBASE_STORAGE_BUCKET%|${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}|g" js/firebase-template.js
          sed -i "s|%VITE_FIREBASE_MESSAGING_SENDER_ID%|${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}|g" js/firebase-template.js
          sed -i "s|%VITE_FIREBASE_APP_ID%|${{ secrets.VITE_FIREBASE_APP_ID }}|g" js/firebase-template.js
          cp js/firebase-template.js js/firebase.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
